# Structured Decoding
steps:
  - label: "Correctness tests for Structured Decoding"
    key: "Structured_Decoding_CorrectnessTest"
    soft_fail: true
    agents:
      queue: tpu_v6e_queue
    commands:
      - .buildkite/scripts/run_in_docker.sh python3 -m pytest -s -v /workspace/tpu_inference/tests/runner/test_structured_decoding_manager.py
  - label: "Record correctness test result for Structured Decoding"
    key: "record_Structured_Decoding_CorrectnessTest"
    depends_on: "Structured_Decoding_CorrectnessTest"
    env:
      CI_TARGET: Structured Decoding
      CI_STAGE: "CorrectnessTest"
    agents:
      queue: cpu
    commands:
      - |
        .buildkite/scripts/record_step_result.sh Structured_Decoding_CorrectnessTest
