x-run-condition: &run-on-nightly-or-tag
  if: build.env("NIGHTLY") == "1" || build.tag =~ /^v?[0-9]+(\.[a-zA-Z0-9]+)*([a-zA-Z]+[0-9]*)?$/

notify:
  - email: "ullm-oncall@rotations.google.com"
    if: build.state == "failed" && build.branch == "main"

steps:
   - label: "Upload Tests for Models & Features"
     <<: *run-on-nightly-or-tag
     agents:
       queue: cpu
     commands:
       - bash .buildkite/scripts/upload_models_and_features.sh

   - wait: ~
     continue_on_failure: true  # ensure we still generate support matrices even if some tests fail

   - label: "Generate support matrices"
     <<: *run-on-nightly-or-tag
     key: generate_support_matrices
     agents:
       queue: cpu
     soft_fail: true
     commands:
       - bash .buildkite/scripts/generate_support_matrices.sh

#   - label: "Notify test results"
##     if: build.env("NIGHTLY") == "1"
#     key: notify_test_results
#     depends_on: generate_support_matrices
#     agents:
#       queue: cpu
#     commands:
#       - bash .buildkite/scripts/notify_test_results.sh

#   - label: "Record verified commit hashes"
#     key: record_verified_commit_hashes
#     depends_on: notify_test_results
#     branches: "main"
#     agents:
#       queue: cpu
#     commands:
#       # TODO : record verified vllm-tpu_inference commit hash pair if test successful (to be handled in separate PR)
#       - echo "committing verified commit hashes"
#
   - label: "Commit support matrices"
     <<: *run-on-nightly-or-tag
     key: commit_nightly_support_matrices
     depends_on: generate_support_matrices
     agents:
       queue: cpu
     secrets:
      - GITHUB_PAT
     command:
       - bash .buildkite/scripts/commit_support_matrices.sh
