notify:
  - email: "ullm-test-notifications-external@google.com"
    if: build.state == "failed" && build.branch == "main"
  - slack: "vllm#tpu-ci-notifications"
    if: build.state == "failed" && build.branch == "main"

steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "E2E MLPerf tests for JAX models"
     key: test_0
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLPerf tests for JAX models with quantization"
     key: test_1
     soft_fail: true
     env:
       QUANTIZATION: "True"
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "E2E MLPerf tests for JAX new models"
     key: test_2
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "E2E MLPerf tests for JAX + vLLM models on single chip"
     key: test_3
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_queue
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "E2E MLperf tests for Llama4 models"
     key: test_4
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
       USE_V6E8_QUEUE: "True"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi


   - label: "E2E multi modality test"
     key: test_5
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/e2e/test_multi_modal_inference.py && \
              bash /workspace/tpu_inference/tests/e2e/benchmarking/mm_bench.sh'
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "E2E speculative decoding test"
     key: test_6
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py'
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi


   - label: "JAX unit tests"
     key: test_7
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v -x /workspace/tpu_inference/tests/ \
           --ignore=/workspace/tpu_inference/tests/kernels \
           --ignore=/workspace/tpu_inference/tests/lora \
           --ignore=/workspace/tpu_inference/tests/e2e \
           --ignore=/workspace/tpu_inference/tpu_inference/mock \
           --ignore=/workspace/tpu_inference/tests/layers/vllm/test_compressed_tensors_moe.py \
           --ignore=/workspace/tpu_inference/tests/distributed/offload \
           --cov-config=/workspace/tpu_inference/.coveragerc --cov tpu_inference --cov-report term-missing --cov-fail-under=69

   - label: "JAX unit tests - kernels"
     key: test_8
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels|tests/kernels|requirements\.txt)'; then
           .buildkite/scripts/run_in_docker.sh \
             python3 -m pytest -s -v -x /workspace/tpu_inference/tests/kernels \
             --ignore=/workspace/tpu_inference/tests/kernels/ragged_paged_attention_kernel_v2_test.py \
             --ignore=/workspace/tpu_inference/tests/kernels/ragged_kv_cache_update_v2_test.py \
             --ignore=/workspace/tpu_inference/tests/kernels/collectives \
             --ignore=/workspace/tpu_inference/tests/kernels/host_dma_test.py \
             --ignore=/workspace/tpu_inference/tests/kernels/fused_moe_v1_test.py
         else
           echo "Skipping: no changes detected in kernels, tests/kernels, or requirements.txt"
           exit 0
         fi

   - label: "JAX unit tests - collective kernels"
     key: test_9
     soft_fail: true
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels/collectives|tests/kernels/collectives|requirements\.txt)'; then
           .buildkite/scripts/run_in_docker.sh \
             python3 -m pytest -s -v -x /workspace/tpu_inference/tests/kernels/collectives
         else
           echo "Skipping: no changes detected in kernels/collectives, tests/kernels/collectives, or requirements.txt"
           exit 0
         fi

   - label: "lora e2e tests for JAX + vLLM models single chip"
     key: test_10
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'MODEL_IMPL_TYPE=vllm TPU_BACKEND_TYPE=jax python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_lora.py'
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "E2E MLPerf tests for JAX + vLLM models on multiple chips"
     key: test_11
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "E2E MLperf tests for DeepSeek-R1 (no accuracy, 12-decoder layers only)"
     key: test_12
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
       USE_V6E8_QUEUE: "True"
       SKIP_ACCURACY_TESTS: "True"
       VLLM_MLA_DISABLE: "1"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh -m deepseek-ai/DeepSeek-R1-0528 --use-dummy-weights
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "lora e2e tests for JAX + vLLM models multi chips"
     key: test_13
     soft_fail: true
     env:
       USE_V6E8_QUEUE: "True"
       VLLM_LOG_LEVEL: "INFO"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'MODEL_IMPL_TYPE=vllm TPU_BACKEND_TYPE=jax python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_lora.py'
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi


   - label: "lora unit tests on single chip"
     key: test_15
     soft_fail: true
     agents:
       queue: tpu_v6e_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           bash -c ' python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_bgmv.py && \
           python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_layers.py'

   - label: "lora unit tests on multi chips"
     key: test_16
     soft_fail: true
     env:
       USE_V6E8_QUEUE: "True"
       VLLM_LOG_LEVEL: "INFO"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]]; then
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_layers.py'
         else
           echo "Skipping: NIGHTLY environment variable not set"
           exit 0
         fi

   - label: "kv cache offload tests on multi chips"
     key: test_17
     soft_fail: true
     env:
       USE_V6E8_QUEUE: "True"
       VLLM_LOG_LEVEL: "INFO"
     agents:
       queue: tpu_v6e_8_queue
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v -x /workspace/tpu_inference/tests/distributed/offload/ \
           /workspace/tpu_inference/tests/kernels/host_dma_test.py \
           --ignore=/workspace/tpu_inference/tests/distributed/offload/tpu_offload_accuracy_test.py
  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "TPU Test Notification"
     key: tpu_test_notification
     depends_on:
       - test_0
       - test_1
       - test_2
       - test_3
       - test_4
       - test_5
       - test_6
       - test_7
       - test_8
       - test_9
       - test_10
       - test_11
       - test_12
       - test_13
       - test_15
       - test_16
       - test_17
     agents:
       queue: cpu
     commands:
       - |
         .buildkite/scripts/check_results.sh \
           "TPU JAX Tests Failed" test_0 test_1 test_2 test_3 test_4 test_5 test_6 test_7 test_8 test_9 test_10 test_11 test_12 test_13 test_15 test_16 test_17
