# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

notify:
  - email: "ullm-test-notifications-external@google.com"
    if: build.state == "failed" && build.branch == "main"
  - slack: "vllm#tpu-ci-notifications"
    if: build.state == "failed" && build.branch == "main"

steps:
  # -----------------------------------------------------------------
  # TEST STEPS - Calling wrapper
  # -----------------------------------------------------------------
   - label: "${LABEL_PREFIX}E2E MLPerf tests for JAX models"
     key: ${KEY_PREFIX}test_0
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "${LABEL_PREFIX}E2E MLPerf tests for JAX models with quantization"
     key: ${KEY_PREFIX}test_1
     soft_fail: true
     env:
       QUANTIZATION: "True"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "${LABEL_PREFIX}E2E MLPerf tests for JAX new models"
     key: ${KEY_PREFIX}test_2
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "${LABEL_PREFIX}E2E MLPerf tests for JAX + vLLM models on single chip"
     key: ${KEY_PREFIX}test_3
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "${LABEL_PREFIX}E2E MLperf tests for Llama4 models"
     key: ${KEY_PREFIX}test_4
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
       USE_V6E8_QUEUE: "True"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

   - label: "${LABEL_PREFIX}E2E speculative decoding test"
     key: ${KEY_PREFIX}test_6
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
           .buildkite/scripts/run_in_docker.sh \
             bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/e2e/test_speculative_decoding.py'

   - label: "${LABEL_PREFIX}JAX unit tests"
     key: ${KEY_PREFIX}test_7
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v -x /workspace/tpu_inference/tests/ \
           --ignore=/workspace/tpu_inference/tests/kernels \
           --ignore=/workspace/tpu_inference/tests/lora \
           --ignore=/workspace/tpu_inference/tests/e2e \
           --ignore=/workspace/tpu_inference/tpu_inference/mock \
           --ignore=/workspace/tpu_inference/tests/layers/vllm/test_compressed_tensors_moe.py \
           --ignore=/workspace/tpu_inference/tests/models/jax/test_deepseek_v3.py \
           --cov-config=/workspace/tpu_inference/.coveragerc --cov tpu_inference --cov-report term-missing --cov-fail-under=${COV_FAIL_UNDER:-69}
   
   - label: "${LABEL_PREFIX}JAX unit tests - 1"
     key: ${KEY_PREFIX}test_7
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v -x \
           /workspace/tpu_inference/tests/core/ \
           /workspace/tpu_inference/tests/executors/ \
           /workspace/tpu_inference/tests/layers/ \
           --cov-config=/workspace/tpu_inference/.coveragerc --cov tpu_inference --cov-report term-missing --cov-fail-under=${COV_FAIL_UNDER:-69}

   - label: "${LABEL_PREFIX}JAX unit tests - 2" 
     key: ${KEY_PREFIX}test_7
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           python3 -m pytest -s -v -x \
           /workspace/tpu_inference/tests/distributed/ \
           /workspace/tpu_inference/tests/experimental/ \
           /workspace/tpu_inference/tests/models/ \
           /workspace/tpu_inference/tests/platforms/ \
           /workspace/tpu_inference/tests/runner/ \
           /workspace/tpu_inference/tests/spec_decode/ \
           /workspace/tpu_inference/tests/worker/ \
           /workspace/tpu_inference/tests/test_envs.py \
           /workspace/tpu_inference/tests/test_tpu_info.py \
           /workspace/tpu_inference/tests/test_utils.py \
           /workspace/tpu_inference/tests/test_base.py \
           --cov-config=/workspace/tpu_inference/.coveragerc --cov tpu_inference --cov-report term-missing --cov-fail-under=${COV_FAIL_UNDER:-69}

   - label: "${LABEL_PREFIX}JAX unit tests - kernels"
     key: ${KEY_PREFIX}test_8
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels|tests/kernels|requirements.txt)'; then
           .buildkite/scripts/run_in_docker.sh \
             python3 -m pytest -s -v -x /workspace/tpu_inference/tests/kernels \
             --ignore=/workspace/tpu_inference/tests/kernels/ragged_paged_attention_kernel_v2_test.py \
             --ignore=/workspace/tpu_inference/tests/kernels/ragged_kv_cache_update_v2_test.py \
             --ignore=/workspace/tpu_inference/tests/kernels/collectives
         else
           echo "Skipping: Step requires either a NIGHTLY build or changes in kernels, kernel tests, or requirements.txt."
           exit 0
         fi

   - label: "${LABEL_PREFIX}JAX unit tests - collective kernels"
     key: ${KEY_PREFIX}test_9
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     commands:
       - |
         if [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels/collectives|tests/kernels/collectives|requirements.txt)'; then
           .buildkite/scripts/run_in_docker.sh \
             python3 -m pytest -s -v -x /workspace/tpu_inference/tests/kernels/collectives
         else
           echo "Skipping: Step requires either a NIGHTLY build or changes in kernels/collectives, tests, or requirements.txt."
           exit 0
         fi

   - label: "${LABEL_PREFIX}lora e2e tests for JAX + vLLM models single chip"
     key: ${KEY_PREFIX}test_10
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash -c 'MODEL_IMPL_TYPE=vllm TPU_BACKEND_TYPE=jax python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_lora.py'

   - label: "${LABEL_PREFIX}E2E MLPerf tests for JAX + vLLM models on multiple chips"
     key: ${KEY_PREFIX}test_11
     soft_fail: true
     env:
       MODEL_IMPL_TYPE: "vllm"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh

  # TODO (jacobplatin): re-enable this after b/467105149 is fixed
   - label: "${LABEL_PREFIX}E2E MLperf tests for DeepSeek-R1 (no accuracy, 12-decoder layers only)"
     key: ${KEY_PREFIX}test_12
     soft_fail: true
     env:
       NEW_MODEL_DESIGN: "1"
       USE_V6E8_QUEUE: "True"
       SKIP_ACCURACY_TESTS: "True"
       VLLM_MLA_DISABLE: "1"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1" && build.env("IS_FOR_V7X") == "true"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/mlperf.sh -m jrplatin/DeepSeek-R1-1D-Subchannel-256  --use-dummy-weights

   - label: "${LABEL_PREFIX}lora e2e tests for JAX + vLLM models multi chips"
     key: ${KEY_PREFIX}test_13
     soft_fail: true
     env:
       TEST_LORA_TP: "True"
       VLLM_LOG_LEVEL: "INFO"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - .buildkite/scripts/run_in_docker.sh bash -c 'MODEL_IMPL_TYPE=vllm TPU_BACKEND_TYPE=jax python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_lora.py'

   - label: "${LABEL_PREFIX}lora unit tests on single chip"
     key: ${KEY_PREFIX}test_15
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_SINGLE:-tpu_v6e_queue}
     commands:
       - |
         .buildkite/scripts/run_in_docker.sh \
           bash -c ' python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_bgmv.py && \
           python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_layers.py'

   - label: "${LABEL_PREFIX}lora unit tests on multi chips"
     key: ${KEY_PREFIX}test_16
     soft_fail: true
     env:
       USE_V6E8_QUEUE: "True"
       VLLM_LOG_LEVEL: "INFO"
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     commands:
       - .buildkite/scripts/run_in_docker.sh bash -c 'python3 -m pytest -s -v -x /workspace/tpu_inference/tests/lora/test_layers.py'

   - label: "${LABEL_PREFIX}E2E lm_eval accuracy check qwen3 coder with fused moe."
     key: ${KEY_PREFIX}test_17
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     commands:
       - |
         if [[ "$$IS_FOR_V7X" == "true" ]] && { [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels|tests/kernels|requirements(_.*)?\.txt)'; }; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8" --use_moe_ep_kernel 1 --tensor_parallel_size 8 --max_model_len 2048 --max_num_batched_tokens 2048 --max_gen_toks 256 --enable_expert_parallel 1 --flex_threshold 0.85 --strict_threshold 0.70
         else
           echo "Skipping: Step requires TPU v7x and either a NIGHTLY build or kernel/requirements changes."
           exit 0
         fi

   - label: "${LABEL_PREFIX}E2E lm_eval accuracy check qwen3 coder with gmm kernel."
     key: ${KEY_PREFIX}test_18
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     commands:
       - |
         if [[ "$$IS_FOR_V7X" == "true" ]] && { [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels|tests/kernels|requirements(_.*)?\.txt)'; }; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8" --use_moe_ep_kernel 0 --tensor_parallel_size 8 --max_model_len 2048 --max_num_batched_tokens 2048 --max_gen_toks 256 --enable_expert_parallel 1 --flex_threshold 0.85 --strict_threshold 0.70
         else
           echo "Skipping: Step requires TPU v7x and either a NIGHTLY build or kernel/requirements changes."
           exit 0
         fi

   - label: "${LABEL_PREFIX}E2E lm_eval accuracy check gpt oss."
     key: ${KEY_PREFIX}test_19
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     commands:
       - |
         if [[ "$$IS_FOR_V7X" == "true" ]] && { [[ "$$NIGHTLY" == "1" ]] || git diff --name-only HEAD~1 | grep -qE '^(tpu_inference/kernels|tests/kernels|requirements(_.*)?\.txt)'; }; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/check_lm_eval.sh  --model_name "openai/gpt-oss-120b" --use_moe_ep_kernel 1 --tensor_parallel_size 8 --max_model_len 2048 --max_num_batched_tokens 2048 --max_gen_toks 256 --enable_expert_parallel 1 --flex_threshold 0.50 --strict_threshold 0.25
         else
           echo "Skipping: Step requires TPU v7x and either a NIGHTLY build or kernel/requirements changes."
           exit 0
         fi

   - label: "${LABEL_PREFIX}Perf regression test for qwen3 coder 1k 8k."
     key: ${KEY_PREFIX}test_20
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - |
         if [[ "$$IS_FOR_V7X" == "true" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/bm_qwen3_coder.sh --model Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8 --tp 8 --req_tput_limit 0.15  --output_token_tput_limit 1170 --total_token_tput_limit 1314 --input_len 1024 --output_len 8192 --use_moe_ep_kernel 1
         fi
  
   - label: "${LABEL_PREFIX}Perf regression test for qwen3 coder 8k 1k."
     key: ${KEY_PREFIX}test_21
     soft_fail: true
     env:
       IS_FOR_V7X: "${IS_FOR_V7X}"
     agents:
       queue: ${TPU_QUEUE_MULTI:-tpu_v6e_8_queue}
     if: build.env("NIGHTLY") == "1"
     commands:
       - |
         if [[ "$$IS_FOR_V7X" == "true" ]]; then
           .buildkite/scripts/run_in_docker.sh bash /workspace/tpu_inference/tests/e2e/benchmarking/bm_qwen3_coder.sh --model Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8 --tp 8 --req_tput_limit 0.4  --output_token_tput_limit 381 --total_token_tput_limit 3421 --input_len 8192 --output_len 1024 --use_moe_ep_kernel 1
         fi
  
  # -----------------------------------------------------------------
  # NOTIFICATION STEP
  # -----------------------------------------------------------------
   - label: "${LABEL_PREFIX}TPU Test Notification"
     key: ${KEY_PREFIX}tpu_test_notification
     depends_on:
       - ${KEY_PREFIX}test_0
       - ${KEY_PREFIX}test_1
       - ${KEY_PREFIX}test_2
       - ${KEY_PREFIX}test_3
       - ${KEY_PREFIX}test_4
       - ${KEY_PREFIX}test_6
       - ${KEY_PREFIX}test_7
       - ${KEY_PREFIX}test_8
       - ${KEY_PREFIX}test_9
       - ${KEY_PREFIX}test_10
       - ${KEY_PREFIX}test_11
       - ${KEY_PREFIX}test_12
       - ${KEY_PREFIX}test_13
       - ${KEY_PREFIX}test_15
       - ${KEY_PREFIX}test_16
       - ${KEY_PREFIX}test_17
       - ${KEY_PREFIX}test_18
       - ${KEY_PREFIX}test_19
       - ${KEY_PREFIX}test_20
       - ${KEY_PREFIX}test_21
     agents:
       queue: cpu
     commands:
       - |
         .buildkite/scripts/check_results.sh \
           "TPU JAX Tests Failed" ${KEY_PREFIX}test_0 ${KEY_PREFIX}test_1 ${KEY_PREFIX}test_2 ${KEY_PREFIX}test_3 ${KEY_PREFIX}test_4 ${KEY_PREFIX}test_6 ${KEY_PREFIX}test_7 ${KEY_PREFIX}test_8 ${KEY_PREFIX}test_9 ${KEY_PREFIX}test_10 ${KEY_PREFIX}test_11 ${KEY_PREFIX}test_12 ${KEY_PREFIX}test_13 ${KEY_PREFIX}test_15 ${KEY_PREFIX}test_16 ${KEY_PREFIX}test_17 ${KEY_PREFIX}test_18 ${KEY_PREFIX}test_19 ${KEY_PREFIX}test_20 ${KEY_PREFIX}test_21
