apiVersion: v1
kind: Pod
metadata:
  name: tpu-job-host-offload-unit-tests
  # This pod runs the distributed unit tests for the TPUOffloadConnector
  # and other related functionalities. It executes all tests found in the
  # tests/distributed/ directory using pytest.
spec:
  restartPolicy: Never
  nodeSelector:
    cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
    cloud.google.com/gke-tpu-topology: 2x4 # Specify the physical topology for the TPU slice.
  containers:
  - name: tpu-job
    image: gcr.io/gke-shared-ai-dev/tpu-inference:cpu-offload
    imagePullPolicy: Always
    command:
    - /bin/bash
    - -c
    - "pytest -sv tests/distributed/offload/"
    env:
    - name: HUGGING_FACE_HUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: hf-token-secret
          key: token
    resources:
      requests:
        google.com/tpu: 8
      limits:
        google.com/tpu: 8
